# setup

["docs:setup"]
depends = ["docs:setup:*"]

["docs:setup:yarn"]
dir = "{{config_root}}/docs"
run = "yarn install"
sources = ["yarn.lock", "package.json"]
outputs = { auto = true }

# check

["docs:check"]
depends = ["docs:check:*"]

["docs:check:links"]
depends = ["docs:setup"]
dir = "{{config_root}}/docs"
run = "yarn mintlify broken-links"
sources = ["**/*.mdx"]
outputs = { auto = true }

["docs:check:snippets"]
depends = ["docs:setup"]
dir = "{{config_root}}/docs"
run = "yarn embedme --source-root=.. ./**/*.mdx --verify --silent"
sources = ["**/*.mdx", "../python/examples/**/*", "../typescript/examples/**/*"]
outputs = { auto = true }

# fix

["docs:fix"]
depends = ["docs:fix:*"]

["docs:fix:snippets"]
depends = ["docs:setup"]
dir = "{{config_root}}/docs"
run = "yarn embedme --source-root=.. ./**/*.mdx --silent"
sources = ["**/*.mdx", "../python/examples/**/*", "../typescript/examples/**/*"]
outputs = { auto = true }

# run

["docs:run"]
dir = "{{config_root}}/docs"
run = "yarn mintlify dev --port 3333"

# git hooks

["docs:git-hooks:pre-commit"]
depends = ["docs:check"]
